config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Dashboards', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Behavior/AuthUserBehavior.php
<?php
namespace App\Model\Behavior;

use Cake\ORM\Behavior;
use Cake\ORM\Table;
use Cake\Network\Session;
use TinyAuth\Auth\AuthUserTrait;
use TinyAuth\Auth\AclTrait;

/**
 * AuthUser behavior
 */
class AuthUserBehavior extends Behavior
{
	use AuthUserTrait, AclTrait;

    /**
     * Default configuration.
     *
     * @var array
     */
    protected $_defaultConfig = [
        'idColumn' => 'id', // ID Column in users table
	'roleColumn' => 'role_id', // Foreign key for the Role ID in users table or in pivot table
	'multiRole' => false,
        'rolesTable' => 'Roles'
    ];

    /**
	 * AuthUser behavior::_getUser()
	 *
	 * @return array
	 */
	protected function _getUser() {
		$session = new Session;
		return (array)$session->read('Auth.User');
	}

}

src/Template/Appointments/appointment_search.ctp
<?php echo $this->Form->create(null, [
    'url' => ['controller' => 'Appointments', 'action' => 'index'],
    'type' => 'get', 'class' => 'form-inline', 'templates' => ['inputContainer' => '{{content}}']
]);
?>
<input type="hidden" name="search_mode" value="appointment_search">
<div class="form-group">
    <label> Doctor</label>
    <?php echo $this->Form->input('doctor_id', [
        'div' => false, 'label' => false, 'class' => 'form-control',
        'multiple' => true, 'id' => 'doc_idsearchdrp',
        'required' => false, 'options' => $doctors, 'value' => $this->request->query('doctor_id')]); ?>
</div>
<div class="form-group date">
   <input type="text" name="appointment_from" class="form-control" placeholder="Appointment From" id="appointment_from" style="width: 140px" 
        value="<?php echo !empty($this->request->query('appointment_from')) ? $this->request->query('appointment_from') : ''; ?>">
</div>
<div class="form-group date">
  <input type="text" name="appointment_to" class="form-control" placeholder="Appointment To" id="appointment_to" style="width: 140px"
         value="<?php echo !empty($this->request->query('appointment_to')) ? $this->request->query('appointment_to') : ''; ?>">
</div>
<button type="submit" class="btn btn-primary">Search</button>
 <?php if (isset($searchActive) && $searchActive === true): ?>
  <a href='<?php echo $this->Url->build(['action' => 'index', '?' => ['clear_search_filter' => true]]); ?>' class="btn btn-danger">
     Clear Filters & Reload
 </a>
 <?php endif; ?>
<?php echo $this->Form->end(); ?>
<?php echo $this->Html->css(['bootstrap-multiselect', '../vendors/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min'],['block'=>'pluginCss']); ?> 
<?php echo $this->Html->script(['bootstrap-multiselect.min', '../vendors/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min'], ['block' => 'pluginJs']); ?>
<?php $this->append('scriptBottom'); ?>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            $('#appointment_from, #appointment_to').datetimepicker({format: 'MM/DD/YYYY', useCurrent: false});
            $('#doc_idsearchdrp').multiselect({
                enableFiltering: true,
                enableClickableOptGroups: true,
                enableCaseInsensitiveFiltering: true,
                nonSelectedText: 'None selected',
                nSelectedText: ' selected',
                allSelectedText: 'All selected',
                includeSelectAllOption: true,
                selectAllText: 'Select All'
            });
        });
    </script>
<?php $this->end(); ?>

src/Template/Appointments/index.ctp
<?php use Cake\Core\Configure; ?>
<!-- page content -->
        <div class="right_col index_page" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Appointments</h3>
              </div>
            </div>
            <div class="clearfix"></div>
            <?= $this->Flash->render() ?>
            <?= $this->Flash->render('auth') ?>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_content">
                         <div class="btn-group">
                            <button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                              <?php $allLeadStatus = Configure::read('allLeadStatus');
                                    $filterText = 'Filter by';
                                    if (is_numeric($this->request->query('status'))
                                            && isset($allLeadStatus[$this->request->query('status')])){
                                        $filterText = $allLeadStatus[$this->request->query('status')];
                                    } elseif(!empty($this->request->query['favorite']) && $this->request->query['favorite'] == 'starred'){
                                        $filterText = 'Starred';
                                    } elseif(!empty($this->request->query['favorite']) && $this->request->query['favorite'] == 'unstarred'){
                                        $filterText = 'Unstarred';
                                    }
                                    echo $filterText;
                                    ?>
                              <span class="caret"></span>
                              <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->Url->build(['action' => 'index', '?' => ['clear_search_filter' => 1]]); ?>">All</a></li>
                                <?php foreach ($apptStatus as $val): 
                                    
                                    ?> 
                                    <li><a href="<?php echo $this->Url->build(['action' => 'index',  "?" => ["status" => $val]]); ?>">
                                        <?php echo $allLeadStatus[$val]; ?>
                                        </a></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                      <div class="btn-group">
                           <?php echo $this->element('../Appointments/appointment_search'); ?>
                      </div>
                  <?php if ($this->AuthUser->hasRoles([ROLE_ADMIN, ROLE_STAFF])): ?>
                   <!--Export button starts-->
                   <div class="btn-group pull-right">
                       <a href="<?php echo $this->Url->build(['action' => 'exportExcel', '?' => $this->request->query]); ?>" target="_blank" class="btn btn-warning">
                        Export To Excel  <i class="fa fa-share"></i> 
                    </a>
                  </div>
                   <!--Export button- ends-->
                  <?php endif; ?>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                      <div class="table-responsive">
                    <table id="appt_list" class="table table-striped table-bordered table-hover sticky_thead">
                      <thead>
                        <tr>
                          <th><?php echo $this->Paginator->sort('id', 'ID'); ?></th>
                          <th><?php echo $this->Paginator->sort('Doctors.Users.first_name', 'Doctor Name'); ?></th>
                          <th><?php echo $this->Paginator->sort('first_name', 'Patient Name'); ?></th>
                          <th>Notes by Eligibility agent</th>
                          <th><?php echo $this->Paginator->sort('appointment', 'Appointment Date'); ?></th>
                          <th><?php echo $this->Paginator->sort('appointment', 'Appointment Time'); ?></th>
                          <th>Status</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php foreach ($leads as $lead): 
                            $link =  $this->Url->build(['controller' => 'Leads', 'action' => 'view', $lead->id]);?>
                          <tr data-lead_id="<?php echo $lead->id; ?>">
                              <td>
                                  <a href="<?=$link?>"  data-toggle="tooltip" title="Click to view more">
                                      <?= '#'.$lead->id; ?>
                                  </a>
                              </td>
                              <td>
                                  <a href="<?=$link?>"  data-toggle="tooltip" title="Click to view more">
                                       <?php if (!empty($lead->doctor->user)){
                                           echo h($lead->doctor->user->full_name);
                                       } ?>
                                  </a>
                                </td>
                                <td><a href="<?=$link?>"  data-toggle="tooltip" title="Click to view more">
                                         <?php echo h($lead->full_name); ?>
                                    </a>
                                 </td>
                                 <td><a href="<?=$link?>"  data-toggle="tooltip" title="Click to view more">
                                        <?php if (!empty($lead->lead_latest_status)){
                                        echo $lead->leadLatestApptStat(['apptStatus' => $apptStatus, 'withNote' => true]); 
                                        } ?>
                                     </a>
                              </td>
                              <td><a href="<?=$link?>"  data-toggle="tooltip" title="Click to view more">
                                       <?php echo $lead->appointment_date; ?>
                                  </a>
                              </td>
                              <td><a href="<?=$link?>"  data-toggle="tooltip" title="Click to view more">
                                       <?php echo $lead->appointment_time; ?>
                                  </a>
                                </td>
                              <td>
                                  <?php $latestApptStat = $lead->leadLatestApptStat(['apptStatus' => $apptStatus]); 
                                  if (!is_null($latestApptStat)) : ?>
                                    <a href="<?=$link?>"  data-toggle="tooltip" title="Click to view more">
                                    <strong class="<?php 
                                      echo !empty($lead->lead_latest_status) ? 
                                        $this->Common->getLeadStatusTextClass($latestApptStat) 
                                              : ''; ?>">
                                          <?php echo  $this->Common->getStatusText($latestApptStat); ?> 
                                      </strong>
                                    </a>
                                  <?php endif; ?>
                              </td>
                          </tr>
                          <?php endforeach; ?>
                         
                      </tbody>
                    </table>
                      </div>
                  </div>
                </div>
              </div>
            </div>
            <?php echo $this->element('pagination'); ?>
          </div>
        </div>
        <!-- /page content -->
        <?php echo $this->Html->script(['jquery.floatThead.min'], ['block' => 'pluginJs']); ?>
        <?php $this->append('scriptBottom'); ?>
        <script type="text/javascript">
            jQuery('document').ready(function(){
            });
        </script>
        <?php $this->end(); ?>